(function(){
  'use strict';
  const STORAGE_KEY='sekkei-projects-v2';
  const INIT_KEY='sekkei-projects-initialized-v1';
  const $=id=>document.getElementById(id);
  const dateFields=['orderDate','materialsDate','drawingStartDate','drawingCompleteDate','energyCompleteDate','confirmationSubmitDate','assessmentSubmitDate','approvalDate','deliveryDate'];
  const formFields=['name','manager','orderAmount','memo','energyRequired','confirmationRequired','assessmentRequired',...dateFields,'billingAmount','billingMonth','invoiceDate','paymentDate'];
  const today=new Date();
  const monthKey=(d,offset=0)=>{const x=new Date(d.getFullYear(),d.getMonth()+offset,1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
  const d=(offset)=>{const x=new Date(today);x.setDate(x.getDate()+offset);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
  const samples=()=>[
    {id:uid(),name:'戸建住宅 A邸',manager:'佐藤',volume:'M',orderAmount:860000,memo:'構造図との整合確認を優先',energyRequired:true,confirmationRequired:true,assessmentRequired:false,orderDate:d(-20),materialsDate:d(-16),drawingStartDate:d(-13),drawingCompleteDate:'',energyCompleteDate:'',confirmationSubmitDate:'',assessmentSubmitDate:'',approvalDate:'',deliveryDate:'',billingAmount:860000,billingMonth:monthKey(today,1),invoiceDate:'',paymentDate:''},
    {id:uid(),name:'戸建住宅 B邸',manager:'田中',volume:'S',orderAmount:520000,memo:'',energyRequired:true,confirmationRequired:false,assessmentRequired:false,orderDate:d(-35),materialsDate:d(-31),drawingStartDate:d(-29),drawingCompleteDate:d(-18),energyCompleteDate:'',confirmationSubmitDate:'',assessmentSubmitDate:'',approvalDate:'',deliveryDate:'',billingAmount:520000,billingMonth:monthKey(today,0),invoiceDate:'',paymentDate:''},
    {id:uid(),name:'青山共同住宅',manager:'佐藤',volume:'L',orderAmount:1850000,memo:'適判質疑対応中',energyRequired:true,confirmationRequired:true,assessmentRequired:true,orderDate:d(-70),materialsDate:d(-66),drawingStartDate:d(-62),drawingCompleteDate:d(-39),energyCompleteDate:d(-32),confirmationSubmitDate:d(-25),assessmentSubmitDate:d(-18),approvalDate:'',deliveryDate:'',billingAmount:1850000,billingMonth:monthKey(today,2),invoiceDate:'',paymentDate:''},
    {id:uid(),name:'△△アパート',manager:'山本',volume:'M',orderAmount:1120000,memo:'納品済み・請求書発行待ち',energyRequired:true,confirmationRequired:true,assessmentRequired:true,orderDate:d(-95),materialsDate:d(-90),drawingStartDate:d(-84),drawingCompleteDate:d(-57),energyCompleteDate:d(-50),confirmationSubmitDate:d(-43),assessmentSubmitDate:d(-40),approvalDate:d(-18),deliveryDate:d(-8),billingAmount:1120000,billingMonth:monthKey(today,0),invoiceDate:'',paymentDate:''},
    {id:uid(),name:'□□事務所 改修',manager:'田中',volume:'S',orderAmount:440000,memo:'入金確認済み',energyRequired:false,confirmationRequired:true,assessmentRequired:false,orderDate:d(-120),materialsDate:d(-116),drawingStartDate:d(-110),drawingCompleteDate:d(-90),energyCompleteDate:'',confirmationSubmitDate:d(-80),assessmentSubmitDate:'',approvalDate:d(-55),deliveryDate:d(-50),billingAmount:440000,billingMonth:monthKey(today,-1),invoiceDate:d(-45),paymentDate:d(-20)},
    {id:uid(),name:'桜町テナントビル',manager:'山本',volume:'L',orderAmount:2300000,memo:'確認申請提出済み',energyRequired:true,confirmationRequired:true,assessmentRequired:false,orderDate:d(-55),materialsDate:d(-51),drawingStartDate:d(-48),drawingCompleteDate:d(-27),energyCompleteDate:d(-22),confirmationSubmitDate:d(-9),assessmentSubmitDate:'',approvalDate:'',deliveryDate:'',billingAmount:2300000,billingMonth:monthKey(today,3),invoiceDate:'',paymentDate:''}
  ];
  function uid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw!==null)return JSON.parse(raw)}catch(e){}if(!localStorage.getItem(INIT_KEY)){const data=samples();localStorage.setItem(INIT_KEY,'1');localStorage.setItem(STORAGE_KEY,JSON.stringify(data));return data}return []}
  let projects=load();let selectedId=null;let billingMonthTouched=false;
  const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
  const shortDate=s=>s?s.replaceAll('-','/'):'—';
  const monthLabel=s=>{if(!s)return '—';const [y,m]=s.split('-');return `${y}/${m}`};
  const isUnbilled=p=>!!p.deliveryDate&&!p.invoiceDate;
  function status(p){
    if(p.paymentDate)return '入金済';if(p.invoiceDate)return '請求済';if(isUnbilled(p))return '未請求';if(p.deliveryDate)return '納品済';if(p.approvalDate)return '下付済';
    if(p.assessmentRequired&&p.assessmentSubmitDate)return '適判中';if(p.confirmationRequired&&p.confirmationSubmitDate)return '確認申請中';
    if(p.confirmationRequired&&p.energyRequired&&p.energyCompleteDate)return '確認申請準備';if(p.energyRequired&&p.drawingCompleteDate&&!p.energyCompleteDate)return '省エネ計算中';
    if(p.drawingStartDate&&!p.drawingCompleteDate)return '作図中';if(p.materialsDate&&!p.drawingStartDate)return '作図準備';if(p.orderDate&&!p.materialsDate)return '資料待ち';return '受注';
  }
  function statusClass(s){if(s==='未請求')return 'status-danger';if(s==='作図中'||s==='作図準備')return 'status-blue';if(s.includes('省エネ')||s.includes('準備'))return 'status-purple';if(s==='確認申請中')return 'status-yellow';if(s==='適判中')return 'status-orange';if(s==='納品済'||s==='下付済')return 'status-green';return 'status-gray'}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(projects))}
  function render(){renderSummary();renderChart();renderFilters();renderTable();requestAnimationFrame(updateOverflowHints)}
  function renderSummary(){
    const thisM=monthKey(today),nextM=monthKey(today,1),unbilled=projects.filter(isUnbilled);
    $('totalCount').innerHTML=`${projects.length}<small>件</small>`;$('activeCount').innerHTML=`${projects.filter(p=>!p.deliveryDate).length}<small>件</small>`;
    $('thisMonthAmount').textContent=yen(sum(projects.filter(p=>p.billingMonth===thisM),'billingAmount'));
    $('nextMonthAmount').textContent=yen(sum(projects.filter(p=>p.billingMonth===nextM),'billingAmount'));
    $('thisMonthLabel').textContent=`${Number(thisM.slice(5))}月の合計`;$('nextMonthLabel').textContent=`${Number(nextM.slice(5))}月の合計`;
    $('unbilledAmount').textContent=yen(sum(unbilled,'billingAmount'));$('unbilledCount').textContent=`${unbilled.length}件の要確認案件`;
  }
  function sum(arr,key){return arr.reduce((a,p)=>a+(Number(p[key])||0),0)}
  function renderChart(){
    const data=Array.from({length:6},(_,i)=>{const key=monthKey(today,i),items=projects.filter(p=>p.billingMonth===key);return{key,planned:sum(items,'billingAmount'),invoiced:sum(items.filter(p=>p.invoiceDate),'billingAmount')}});
    const max=Math.max(...data.map(x=>x.planned),1);
    $('billingChart').innerHTML=data.map(x=>`<div class="month-column"><div class="month-values"><strong>${yen(x.planned)}</strong><span>請求済 ${yen(x.invoiced)}</span></div><div class="bar-stage"><i class="bar plan" style="height:${Math.max(2,x.planned/max*100)}%" title="予定 ${yen(x.planned)}"></i><i class="bar invoiced" style="height:${Math.max(2,x.invoiced/max*100)}%" title="請求済 ${yen(x.invoiced)}"></i></div><div class="month-label">${Number(x.key.slice(5))}月</div></div>`).join('')+`<div class="chart-legend" style="grid-column:1/-1"><span><i style="background:#a6b4af"></i>請求予定</span><span><i style="background:#334f48"></i>請求済</span></div>`;
  }
  function renderFilters(){
    const current=$('managerFilter').value;const managers=[...new Set(projects.map(p=>p.manager).filter(Boolean))].sort();$('managerFilter').innerHTML='<option value="">すべて</option>'+managers.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('');
    const currentS=$('statusFilter').value;const statuses=[...new Set(projects.map(status))];$('statusFilter').innerHTML='<option value="">すべて</option>'+statuses.map(x=>`<option ${x===currentS?'selected':''}>${x}</option>`).join('');
  }
  function filtered(){const q=$('searchInput').value.trim().toLowerCase(),m=$('managerFilter').value,s=$('statusFilter').value,u=$('unbilledFilter').checked;return projects.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!m||p.manager===m)&&(!s||status(p)===s)&&(!u||isUnbilled(p)))}
  function stage(p,key,required=true){if(!required)return '<span class="process">対象外</span>';return `<span class="process ${p[key]?'done':''}">${p[key]?'● '+shortDate(p[key]):'未完了'}</span>`}
  function renderTable(){const items=filtered();$('resultCount').textContent=`${items.length}件を表示`;$('emptyState').hidden=items.length>0;$('projectRows').innerHTML=items.map(p=>{const s=status(p);return `<tr><td><button class="project-link" data-open="${p.id}">${esc(p.name)}</button></td><td>${esc(p.manager)}</td><td><span class="status ${statusClass(s)}">${s==='未請求'?'⚠ ':''}${s}</span></td><td>${shortDate(p.orderDate)}</td><td>${stage(p,'materialsDate')}</td><td>${stage(p,'drawingCompleteDate')}</td><td>${stage(p,'energyCompleteDate',p.energyRequired)}</td><td>${stage(p,'confirmationSubmitDate',p.confirmationRequired)}</td><td>${stage(p,'assessmentSubmitDate',p.assessmentRequired)}</td><td>${stage(p,'approvalDate',p.confirmationRequired)}</td><td>${stage(p,'deliveryDate')}</td><td>${monthLabel(p.billingMonth)}</td><td class="amount">${yen(p.billingAmount)}</td><td><span class="status ${isUnbilled(p)?'status-danger':p.paymentDate?'status-gray':p.invoiceDate?'status-green':'status-gray'}">${isUnbilled(p)?'⚠ 未請求':p.paymentDate?'入金済':p.invoiceDate?'請求済':'未請求前'}</span></td><td><button class="row-action" data-open="${p.id}" aria-label="${esc(p.name)}の詳細">›</button></td></tr>`}).join('')}
  function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function openForm(p=null){$('projectForm').reset();$('formTitle').textContent=p?'案件を編集':'案件を追加';$('projectId').value=p?.id||'';billingMonthTouched=false;formFields.forEach(k=>{const el=$(k);if(!el)return;if(k.endsWith('Required'))el.value=String(p?p[k]:true);else el.value=p?.[k]??''});updateScopes();$('projectDialog').showModal();syncModalState();setTimeout(()=>$('name').focus(),0)}
  function updateScopes(){['energy','confirmation','assessment'].forEach(x=>document.querySelectorAll(`[data-scope="${x}"]`).forEach(el=>el.classList.toggle('scope-off',$(x+'Required').value==='false')))}
  function submitForm(e){e.preventDefault();if(!$('projectForm').reportValidity())return;const id=$('projectId').value||uid();const p={id};formFields.forEach(k=>{const el=$(k);p[k]=k.endsWith('Required')?el.value==='true':(k.includes('Amount')?Number(el.value)||0:el.value.trim())});const i=projects.findIndex(x=>x.id===id);if(i>=0)projects[i]=p;else projects.unshift(p);save();render();$('projectDialog').close();toast(i>=0?'案件を更新しました':'案件を登録しました')}
  const timelineDefs=[['受注','orderDate',true],['作図資料受領','materialsDate',true],['作図開始','drawingStartDate',true],['作図完了','drawingCompleteDate',true],['省エネ計算完了','energyCompleteDate','energyRequired'],['確認申請提出','confirmationSubmitDate','confirmationRequired'],['省エネ適判提出','assessmentSubmitDate','assessmentRequired'],['確認申請下付','approvalDate','confirmationRequired'],['最終図面納品','deliveryDate',true]];
  function openDetail(id){const p=projects.find(x=>x.id===id);if(!p)return;selectedId=id;$('detailTitle').textContent=p.name;$('detailMeta').innerHTML=`<span>担当：${esc(p.manager)}</span><span class="status ${statusClass(status(p))}">${status(p)}</span>`;$('timeline').innerHTML=timelineDefs.map(([label,key,req])=>{const required=req===true||p[req];return `<div class="timeline-item ${p[key]?'complete':''} ${!required?'excluded':''}"><span class="timeline-dot">${p[key]?'✓':'○'}</span><div class="timeline-content"><strong>${label}</strong><span>${!required?'対象外':p[key]?shortDate(p[key]):'未完了'}</span></div></div>`}).join('');$('billingDetail').innerHTML=`<h3>受注・請求情報</h3><dl><dt>受注金額</dt><dd>${yen(p.orderAmount)}</dd><dt>請求予定月</dt><dd>${monthLabel(p.billingMonth)}</dd><dt>請求予定額</dt><dd>${yen(p.billingAmount)}</dd><dt>請求日</dt><dd>${shortDate(p.invoiceDate)}</dd><dt>入金日</dt><dd>${shortDate(p.paymentDate)}</dd></dl>${isUnbilled(p)?'<div class="warning">最終図面は納品済みですが、請求日が未入力です。</div>':''}${p.memo?`<h3 style="margin-top:22px">メモ</h3><p style="font-size:.78rem;color:var(--muted)">${esc(p.memo)}</p>`:''}`;$('detailDialog').showModal();syncModalState()}
  function deleteSelected(){const p=projects.find(x=>x.id===selectedId);if(!p)return;if(!confirm('この案件を削除しますか？'))return;projects=projects.filter(x=>x.id!==selectedId);save();render();$('detailDialog').close();toast('案件を削除しました')}
  let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
  function syncModalState(){document.body.classList.toggle('modal-open',!!document.querySelector('.dialog[open]'))}
  function updateOverflowHints(){document.querySelectorAll('[data-scroll-shell]').forEach(shell=>{const region=shell.querySelector('[data-scroll-region]');if(!region)return;const canScrollRight=region.scrollWidth-region.clientWidth-region.scrollLeft>2;shell.classList.toggle('can-scroll-right',canScrollRight)})}
  $('addProject').addEventListener('click',()=>openForm());$('projectForm').addEventListener('submit',submitForm);document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>$('projectDialog').close()));document.querySelectorAll('[data-detail-close]').forEach(x=>x.addEventListener('click',()=>$('detailDialog').close()));
  ['energyRequired','confirmationRequired','assessmentRequired'].forEach(id=>$(id).addEventListener('change',updateScopes));$('billingMonth').addEventListener('input',()=>billingMonthTouched=true);$('deliveryDate').addEventListener('change',e=>{if(e.target.value&&(!billingMonthTouched||!$('billingMonth').value))$('billingMonth').value=e.target.value.slice(0,7)});
  $('projectRows').addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openDetail(b.dataset.open)});$('editProject').addEventListener('click',()=>{const p=projects.find(x=>x.id===selectedId);$('detailDialog').close();openForm(p)});$('deleteProject').addEventListener('click',deleteSelected);
  ['searchInput','managerFilter','statusFilter','unbilledFilter'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',renderTable));$('clearFilters').addEventListener('click',()=>{$('searchInput').value='';$('managerFilter').value='';$('statusFilter').value='';$('unbilledFilter').checked=false;renderTable()});
  document.querySelectorAll('.dialog').forEach(dlg=>dlg.addEventListener('close',syncModalState));
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const open=[...document.querySelectorAll('.dialog[open]')];if(!open.length)return;e.preventDefault();open.at(-1).close();syncModalState()},{capture:true});
  document.querySelectorAll('[data-scroll-region]').forEach(region=>region.addEventListener('scroll',updateOverflowHints,{passive:true}));window.addEventListener('resize',updateOverflowHints);
  [$('projectDialog'),$('detailDialog')].forEach(dlg=>dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()}));render();
})();
